### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by xichaoqiang** [mogiso/AmplitudeSourceLocation#1]
Dear Sir

Your code about amplitude source is very helpful to me.

Is there some more code about travel time source location about double difference?

There only one code about travel time source location.

Best regards,
Xi

**Comment by mogiso** [comment]
Dear Xi-san,

Thank you for your comment.
I am interested in locating events using seismic amplitudes, so I have no plan to develop source location program using travel times at present.  

Regards,
Masashi Ogiso

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
